"""
FixSuggester — LLM-powered auto-fix suggestions for the Tables/Charts Validator.

When operating in LLM-Assisted mode, each finding can have 1-3 fix suggestions
generated by Cascade 2 (or escalated to cloud models). Suggestions require
human approval before any workbook changes are applied.
"""
from __future__ import annotations

import json
import logging
import os
import time
from dataclasses import dataclass, field, asdict
from typing import List, Optional, Dict, Any

from core.models import Finding
from core.mode_manager import ModeManager, OperatingMode

logger = logging.getLogger(__name__)

_DEFAULT_CONFIDENCE_THRESHOLD = 0.5
_DEFAULT_MAX_SUGGESTIONS = 3


@dataclass
class FixSuggestion:
    """A single LLM-generated fix suggestion for a finding."""
    finding_id: str
    rule_id: str
    description: str
    description_fr: str
    proposed_change: str
    proposed_change_fr: str
    confidence: float  # 0.0–1.0
    applies_to: str  # e.g., "B2", "sheet_property:gridlines", "workbook"
    validation_status: str = "pending"  # pending, validated, invalid
    source_model: str = ""
    rejected_reason: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class FixResult:
    """Result of applying a fix suggestion."""
    success: bool
    message: str
    message_fr: str
    error: Optional[str] = None


class FixSuggester:
    """
    Generates and manages fix suggestions for findings.

    Uses the local Cascade 2 model via LiteLLM. Falls back to cloud models
    when confidence is insufficient or local model unavailable.
    """

    def __init__(
        self,
        mode_manager: Optional[ModeManager] = None,
        confidence_threshold: Optional[float] = None,
        max_suggestions: Optional[int] = None,
    ):
        self._mode_manager = mode_manager or ModeManager()
        self._confidence_threshold = confidence_threshold or float(
            os.environ.get("CONFIDENCE_THRESHOLD", str(_DEFAULT_CONFIDENCE_THRESHOLD))
        )
        self._max_suggestions = max_suggestions or int(
            os.environ.get("MAX_SUGGESTIONS_PER_FINDING", str(_DEFAULT_MAX_SUGGESTIONS))
        )
        self._suggestion_cache: Dict[str, List[FixSuggestion]] = {}
        self._litellm = None

        try:
            import litellm  # noqa: F401
            self._litellm = litellm
        except ImportError:
            logger.warning("litellm not installed — fix suggestions disabled")

    # ---- Public API -------------------------------------------------

    def suggest_fixes(
        self,
        finding: Finding,
        workbook_context: str = "",
    ) -> List[FixSuggestion]:
        """
        Generate fix suggestions for a single finding.

        Args:
            finding: The finding to suggest fixes for.
            workbook_context: Optional text describing workbook structure/contents.

        Returns:
            List of FixSuggestion objects (may be empty if LLM unavailable
            or confidence below threshold).
        """
        # Check cache first
        cache_key = finding.finding_id
        if cache_key in self._suggestion_cache:
            return self._suggestion_cache[cache_key]

        if not self._litellm:
            logger.debug("litellm not available — no suggestions for %s", finding.finding_id)
            return []

        mode = self._mode_manager.get_mode()
        if mode == OperatingMode.OFFLINE:
            logger.debug("Offline mode — no suggestions for %s", finding.finding_id)
            return []

        # Build the prompt
        prompt = self._build_prompt(finding, workbook_context)

        # Try local model first
        suggestions = self._call_llm_for_suggestions(
            finding=finding,
            prompt=prompt,
            model=self._mode_manager.cascade2_model,
            base_url=self._mode_manager.litellm_url,
        )

        # Check confidence — escalate to cloud if needed
        if suggestions:
            avg_conf = sum(s.confidence for s in suggestions) / len(suggestions)
            if avg_conf < self._confidence_threshold:
                if self._mode_manager.escalate_to_cloud():
                    logger.info("Low confidence (%.2f) — escalating to cloud model", avg_conf)
                    cloud_suggestions = self._call_llm_for_suggestions(
                        finding=finding,
                        prompt=prompt,
                        model=self._mode_manager.cloud_model,
                        base_url=self._mode_manager.litellm_url,
                    )
                    if cloud_suggestions:
                        for s in cloud_suggestions:
                            s.source_model = f"cloud:{self._mode_manager.cloud_model}"
                        suggestions = cloud_suggestions

        # Validate suggestions
        for s in suggestions:
            s.validation_status = "validated" if s.confidence >= self._confidence_threshold else "pending"

        # Cache results
        self._suggestion_cache[cache_key] = suggestions
        return suggestions

    def apply_suggestion(
        self,
        workbook_path: str,
        suggestion: FixSuggestion,
    ) -> FixResult:
        """
        Apply a validated fix suggestion to the workbook.

        Args:
            workbook_path: Path to the .xlsx file.
            suggestion: The FixSuggestion to apply.

        Returns:
            FixResult indicating success/failure.
        """
        if suggestion.validation_status == "invalid":
            return FixResult(
                success=False,
                message="Suggestion is marked invalid and cannot be applied.",
                message_fr="La suggestion est marquée comme invalide et ne peut pas être appliquée.",
            )

        try:
            import openpyxl
            wb = openpyxl.load_workbook(workbook_path)

            # Parse the proposed change
            change = suggestion.proposed_change.strip()

            # Determine what to modify based on applies_to
            if suggestion.applies_to.startswith("sheet_property:"):
                prop = suggestion.applies_to.split(":", 1)[1]
                # Sheet-level targets must identify the worksheet explicitly:
                # ``sheet_property:<sheet>.<property>``.  Reject ambiguous
                # suggestions rather than silently modifying the active sheet.
                target = prop.split(".", 1)
                if len(target) != 2 or target[0] not in wb.sheetnames:
                    return FixResult(
                        success=False,
                        message="Sheet property target must be '<sheet>.<property>'.",
                        message_fr="La cible de propriété doit être '<feuille>.<propriété>'.",
                    )
                ws = wb[target[0]]
                if target[1] == "gridlines":
                    ws.sheet_view.showGridLines = str(change).lower() in {"true", "1", "yes", "on"}
                else:
                    return FixResult(
                        success=False,
                        message=f"Unsupported sheet property '{target[1]}'.",
                        message_fr=f"Propriété de feuille non prise en charge : '{target[1]}'.",
                    )

            elif ":" in suggestion.applies_to:
                # Cell reference format: "SheetName:A1"
                parts = suggestion.applies_to.split(":", 1)
                sheet_ref = parts[0]
                cell_ref = parts[1]
                if "!" in cell_ref:
                    sheet_ref, cell_ref = cell_ref.split("!", 1)
                if sheet_ref in wb.sheetnames:
                    ws = wb[sheet_ref]
                    ws[cell_ref] = change
                    logger.info("Applied fix to %s!%s: %s", sheet_ref, cell_ref, change[:50])
                else:
                    return FixResult(
                        success=False,
                        message=f"Sheet '{sheet_ref}' not found in workbook.",
                        message_fr=f"Feuille '{sheet_ref}' introuvable dans le classeur.",
                    )
            else:
                # Try treating applies_to as cell ref on first sheet
                ws = wb.active
                try:
                    ws[suggestion.applies_to] = change
                    logger.info("Applied fix to %s: %s", suggestion.applies_to, change[:50])
                except (ValueError, TypeError):
                    return FixResult(
                        success=False,
                        message=f"Cannot apply change to '{suggestion.applies_to}'.",
                        message_fr=f"Impossible d'appliquer la modification à '{suggestion.applies_to}'.",
                    )

            wb.save(workbook_path)
            return FixResult(
                success=True,
                message=f"Fix applied: {suggestion.description}",
                message_fr=f"Correctif appliqué : {suggestion.description_fr}",
            )

        except Exception as e:
            logger.error("Failed to apply suggestion: %s", e)
            return FixResult(
                success=False,
                message=f"Failed to apply fix: {e}",
                message_fr=f"Échec de l'application du correctif : {e}",
                error=str(e),
            )

    def clear_cache(self) -> None:
        """Clear suggestion cache."""
        self._suggestion_cache.clear()

    # ---- Internal ---------------------------------------------------

    def _build_prompt(self, finding: Finding, workbook_context: str = "") -> str:
        """Build the LLM prompt for fix suggestion generation."""
        prompt = f"""You are a Statistics Canada publication formatting expert.
A Tables 101 or Charts 101 rule violation has been detected.

VIOLATION DETAILS:
- Rule: {finding.rule_id} ({finding.pack})
- Severity: {finding.severity.value}
- Sheet: {finding.sheet_name}
- Location: {finding.location}
- Title (EN): {finding.title_en}
- Title (FR): {finding.title_fr}
- Description (EN): {finding.description_en}
- Description (FR): {finding.description_fr}

TASK: Suggest up to {self._max_suggestions} practical fixes for this violation.
Each fix must be a concrete, specific change that can be applied to an Excel workbook cell or property.

For each suggestion, provide:
1. A short description of the fix (in English and French)
2. The exact proposed change (e.g., cell value to set, property to toggle)
3. Where the change applies (cell reference like "Sheet1!B2" or property like "sheet_property:gridlines")
4. A confidence score (0.0–1.0) based on how certain you are this fix is correct

Workbook context (if available): {workbook_context}

IMPORTANT: 
- Never suggest deleting data or removing entire rows/columns
- Keep changes minimal and targeted
- Prefer the French description (description_fr) for French-language workbooks
- Return ONLY valid JSON in this exact format:
{{"suggestions": [{{"description": "...", "description_fr": "...", "proposed_change": "...", "proposed_change_fr": "...", "applies_to": "...", "confidence": 0.0}}]}}
"""
        return prompt

    def _call_llm_for_suggestions(
        self,
        finding: Finding,
        prompt: str,
        model: str,
        base_url: str,
    ) -> List[FixSuggestion]:
        """Call the LLM and parse suggestions from the response."""
        if not self._litellm:
            return []

        try:
            response = self._litellm.completion(
                model=f"openai/{model}" if "/" not in model else model,
                base_url=base_url,
                api_key=os.environ.get("LITELLM_API_KEY", "sk-placeholder"),
                messages=[
                    {"role": "system", "content": "You are a Statistics Canada formatting expert. Respond with valid JSON only."},
                    {"role": "user", "content": prompt},
                ],
                timeout=90,
                temperature=0.3,
                max_tokens=2000,
            )

            content = response.choices[0].message.content.strip()
            data = json.loads(content)

            suggestions = []
            for item in data.get("suggestions", []):
                suggestions.append(FixSuggestion(
                    finding_id=finding.finding_id,
                    rule_id=finding.rule_id,
                    description=item.get("description", "No description"),
                    description_fr=item.get("description_fr", item.get("description", "Aucune description")),
                    proposed_change=item.get("proposed_change", ""),
                    proposed_change_fr=item.get("proposed_change_fr", item.get("proposed_change", "")),
                    confidence=float(item.get("confidence", 0.5)),
                    applies_to=item.get("applies_to", ""),
                    source_model=model,
                ))

            return suggestions

        except Exception as e:
            logger.warning("LLM suggestion call failed (model=%s): %s", model, e)
            return []

    def __repr__(self) -> str:
        return (
            f"FixSuggester(threshold={self._confidence_threshold}, "
            f"max_suggestions={self._max_suggestions}, "
            f"cached={len(self._suggestion_cache)} findings)"
        )